---
- name: Converge
  hosts: all
  become: true

  vars:
    erasure_code_profile:
      ec-profile:
        k: 2
        m: 1
        crush_failure_domain: host
    erasure_pool:
      erasure_pool:
        pg_num: 64
        erasure_code_profile: ec-profile
        pg_autoscale_mode: "off"
        application: rgw
    replicated_pool:
      replicated_pool:
        pg_num: 64
        pg_autoscale_mode: "on"
        application: rgw

  roles:
    - role: ansible-role-ceph-pools
