---
dependency:
  name: shell
  command: rm -rf $MOLECULE_EPHEMERAL_DIRECTORY/ceph-ansible/; git clone --depth 1 --branch v4.0.48 https://github.com/ceph/ceph-ansible.git $MOLECULE_EPHEMERAL_DIRECTORY/ceph-ansible/
driver:
  name: openstack
lint: |
  set -e
  yamllint -c molecule/yaml-lint.yml .
  ansible-lint -c molecule/ansible-lint.yml .
  flake8
platforms:
  - name: "mon-${MON:-1}"
    image: CentOS 7.9 x86_64
    ssh_user: centos
    flavor: m1.medium
    network: kcoakley_network
    groups:
      - mons
      - mgrs
  - name: "osd-${OSD1:-1}"
    image: CentOS 7.9 x86_64
    ssh_user: centos
    flavor: m1.medium
    network: kcoakley_network
    groups:
      - osds
  - name: "osd-${OSD2:-2}"
    image: CentOS 7.9 x86_64
    ssh_user: centos
    flavor: m1.medium
    network: kcoakley_network
    groups:
      - osds
  - name: "osd-${OSD3:-3}"
    image: CentOS 7.9 x86_64
    ssh_user: centos
    flavor: m1.medium
    network: kcoakley_network
    groups:
      - osds
provisioner:
  name: ansible
  log: true
  options:
    vvv: false
  env:
    ANSIBLE_CONFIG: $MOLECULE_EPHEMERAL_DIRECTORY/ceph-ansible/ansible.cfg
  inventory:
    group_vars:
      all:
        containerized_deployment: true
        configure_firewall: false
        ntp_service_enabled: false
        monitor_interface: eth0
        radosgw_interface: eth0
        public_network: 192.168.0.0/24
        cluster_network: 192.168.0.0/24
        osd_objectstore: bluestore
        dashboard_enabled: false
        devices:
          - /dev/vdb
scenario:
  name: default
verifier:
  name: ansible
