---
- name: include the ceph-ansible playbook
  import_playbook: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ceph-ansible/site.yml.sample"

- name: Converge
  hosts: all
  become: true

  vars:
    cluster: ceph
    mon_group_name: mons

  post_tasks:
    - name: Give Ceph time to work
      pause: seconds=5

    - name: Check ceph health
      command: "ceph --connect-timeout 5 --cluster {{ cluster }} health"
      changed_when: false
      delegate_to: "{{ groups[mon_group_name][0] }}"
      register: ceph_health
      until: ceph_health is succeeded
      run_once: true
      failed_when: "'HEALTH_OK' not in ceph_health.stdout"
