---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: set cluster
      set_fact:
        cluster: ceph

    - name: set mon_group_name
      set_fact:
        mon_group_name: mons

    - name: set_fact container_binary
      set_fact:
        container_binary: "{{ 'podman' if (ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8') else 'docker' }}"
      when: containerized_deployment | default(false) | bool

    - name: set_fact container_exec_cmd
      set_fact:
        container_exec_cmd: "{{ container_binary }} exec ceph-mon-{{ hostvars[groups[mon_group_name][0]]['ansible_hostname'] }}"
      when: containerized_deployment | default(false) | bool

    - name: Verify erasure_pool & replicated_pool was created
      command: >-
        {{ container_exec_cmd | default('') }}
        ceph
        --connect-timeout 5
        --cluster {{ cluster }}
        osd pool ls
        -f json
      changed_when: false
      delegate_to: "{{ groups[mon_group_name][0] }}"
      register: pool_list
      until: pool_list is succeeded
      run_once: true
      failed_when: "'erasure_pool' not in (pool_list.stdout | from_json) or 'replicated_pool' not in (pool_list.stdout | from_json)"

    - name: Check ceph health
      command: >-
        {{ container_exec_cmd | default('') }}
        ceph
        --connect-timeout 5
        --cluster {{ cluster }}
        health
      changed_when: false
      delegate_to: "{{ groups[mon_group_name][0] }}"
      register: ceph_health
      until: ceph_health is succeeded
      run_once: true
      failed_when: "'HEALTH_OK' not in ceph_health.stdout"
